from turtle import *
import turtle as tur
import random
import math
tur.width(10)
tur.bgcolor("black")
tur.setup(900, 500)
tur.title("Python SCREBLES")
a1 = tur.Turtle()
b1 = tur.Turtle()
c1 = tur.Turtle()
d1 = tur.Turtle()
e1 = tur.Turtle()
a1 = tur.Turtle()
b1 = tur.Turtle()
c1 = tur.Turtle()
d1 = tur.Turtle()
e1 = tur.Turtle()

a2 = tur.Turtle()
b2 = tur.Turtle()
c2 = tur.Turtle()
d2 = tur.Turtle()
e2 = tur.Turtle()
a2 = tur.Turtle()
b2 = tur.Turtle()
c2 = tur.Turtle()
d2 = tur.Turtle()
e2 = tur.Turtle()
a1 = tur.Turtle()
b1 = tur.Turtle()
c1 = tur.Turtle()
d1 = tur.Turtle()
e1 = tur.Turtle()
a1 = tur.Turtle()
b1 = tur.Turtle()
c1 = tur.Turtle()
d1 = tur.Turtle()
e1 = tur.Turtle()

a2 = tur.Turtle()
b2 = tur.Turtle()
c2 = tur.Turtle()
d2 = tur.Turtle()
e2 = tur.Turtle()
a2 = tur.Turtle()
b2 = tur.Turtle()
c2 = tur.Turtle()
d2 = tur.Turtle()
e2 = tur.Turtle()
a1.color('blue')
b1.color('orange')
c1.color('purple')
d1.color('yellow')
e1.color('red')
a2.color('white')
b2.color('gold')
c2.color('sienna')
d2.color('green')
e2.color('lightgreen')
a1.color('blue')
b1.color('orange')
c1.color('purple')
d1.color('yellow')
e1.color('red')
a2.color('white')
b2.color('gold')
c2.color('sienna')
d2.color('green')
e2.color('lightgreen')
a1.color('blue')
b1.color('orange')
c1.color('purple')
d1.color('yellow')
e1.color('red')
a2.color('white')
b2.color('gold')
c2.color('sienna')
d2.color('green')
e2.color('lightgreen')
a1.color('blue')
b1.color('orange')
c1.color('purple')
d1.color('yellow')
e1.color('red')
a2.color('white')
b2.color('gold')
c2.color('sienna')
d2.color('green')
e2.color('lightgreen')
turtlist = []
turtlist.append(a1)
turtlist.append(b1)
turtlist.append(c1)
turtlist.append(d1)
turtlist.append(e1)
turtlist.append(a1)
turtlist.append(b1)
turtlist.append(c1)
turtlist.append(d1)
turtlist.append(e1)
turtlist.append(a1)
turtlist.append(b1)
turtlist.append(c1)
turtlist.append(d1)
turtlist.append(e1)
turtlist.append(a1)
turtlist.append(b1)
turtlist.append(c1)
turtlist.append(d1)
turtlist.append(e1)
turtlist.append(a2)
turtlist.append(b2)
turtlist.append(c2)
turtlist.append(d2)
turtlist.append(e2)
turtlist.append(a2)
turtlist.append(b2)
turtlist.append(c2)
turtlist.append(d2)
turtlist.append(e2)
turtlist.append(a2)
turtlist.append(b2)
turtlist.append(c2)
turtlist.append(d2)
turtlist.append(e2)

tur.begin_fill()
tur.speed(10000000000000000)
tur.tracer(10000000000000000)
tur.hideturtle()
sum = 0
count = 0
for j in range(1000000000000000):
    for i in range(1000000000000000):
        for turt in turtlist:
            turt.seth(random.randrange(1,350,30))
            turt.fd(10)
        tur.update()
    for turt in turtlist:
        sum += math.sqrt(turt.xcor()*turt.xcor() + turt.ycor()*turt.ycor())/10*2*math.sqrt(turt.xcor()*turt.xcor() + turt.ycor()*turt.ycor())/10*2/100
        count += 1
    for turt in turtlist:
        turt.clear()
        turt.up()
        turt.goto(0,0)
        turt.down()
tur.end_fill()
print("i am done!")
tur.width(10)
tur.bgcolor("black")
tur.setup(900, 500)
tur.title("Python SCREBLES")
a1 = tur.Turtle()
b1 = tur.Turtle()
c1 = tur.Turtle()
d1 = tur.Turtle()
e1 = tur.Turtle()
a1 = tur.Turtle()
b1 = tur.Turtle()
c1 = tur.Turtle()
d1 = tur.Turtle()
e1 = tur.Turtle()

a2 = tur.Turtle()
b2 = tur.Turtle()
c2 = tur.Turtle()
d2 = tur.Turtle()
e2 = tur.Turtle()
a2 = tur.Turtle()
b2 = tur.Turtle()
c2 = tur.Turtle()
d2 = tur.Turtle()
e2 = tur.Turtle()
a1 = tur.Turtle()
b1 = tur.Turtle()
c1 = tur.Turtle()
d1 = tur.Turtle()
e1 = tur.Turtle()
a1 = tur.Turtle()
b1 = tur.Turtle()
c1 = tur.Turtle()
d1 = tur.Turtle()
e1 = tur.Turtle()

a2 = tur.Turtle()
b2 = tur.Turtle()
c2 = tur.Turtle()
d2 = tur.Turtle()
e2 = tur.Turtle()
a2 = tur.Turtle()
b2 = tur.Turtle()
c2 = tur.Turtle()
d2 = tur.Turtle()
e2 = tur.Turtle()
a1.color('blue')
b1.color('orange')
c1.color('purple')
d1.color('yellow')
e1.color('red')
a2.color('white')
b2.color('gold')
c2.color('sienna')
d2.color('green')
e2.color('lightgreen')
a1.color('blue')
b1.color('orange')
c1.color('purple')
d1.color('yellow')
e1.color('red')
a2.color('white')
b2.color('gold')
c2.color('sienna')
d2.color('green')
e2.color('lightgreen')
a1.color('blue')
b1.color('orange')
c1.color('purple')
d1.color('yellow')
e1.color('red')
a2.color('white')
b2.color('gold')
c2.color('sienna')
d2.color('green')
e2.color('lightgreen')
a1.color('blue')
b1.color('orange')
c1.color('purple')
d1.color('yellow')
e1.color('red')
a2.color('white')
b2.color('gold')
c2.color('sienna')
d2.color('green')
e2.color('lightgreen')
turtlist = []
turtlist.append(a1)
turtlist.append(b1)
turtlist.append(c1)
turtlist.append(d1)
turtlist.append(e1)
turtlist.append(a1)
turtlist.append(b1)
turtlist.append(c1)
turtlist.append(d1)
turtlist.append(e1)
turtlist.append(a1)
turtlist.append(b1)
turtlist.append(c1)
turtlist.append(d1)
turtlist.append(e1)
turtlist.append(a1)
turtlist.append(b1)
turtlist.append(c1)
turtlist.append(d1)
turtlist.append(e1)
turtlist.append(a2)
turtlist.append(b2)
turtlist.append(c2)
turtlist.append(d2)
turtlist.append(e2)
turtlist.append(a2)
turtlist.append(b2)
turtlist.append(c2)
turtlist.append(d2)
turtlist.append(e2)
turtlist.append(a2)
turtlist.append(b2)
turtlist.append(c2)
turtlist.append(d2)
turtlist.append(e2)

tur.begin_fill()
tur.speed(10000000000000000)
tur.tracer(10000000000000000)
tur.hideturtle()
sum = 0
count = 0
for j in range(100000000):
    for i in range(1000000000):
        for turt in turtlist:
            turt.seth(random.randrange(1,350,30))
            turt.fd(10)
        tur.update()
    for turt in turtlist:
        sum += math.sqrt(turt.xcor()*turt.xcor() + turt.ycor()*turt.ycor())/10*2*math.sqrt(turt.xcor()*turt.xcor() + turt.ycor()*turt.ycor())/10*2/100
        count += 1
    for turt in turtlist:
        turt.clear()
        turt.up()
        turt.goto(0,0)
        turt.down()
tur.end_fill()
print("i am done!")
